### ISSUE TITLE
Github account

### ISSUE THREAD

**Issue by franciscop** [libre/libre.github.io#1]
Hi @tuxy , I am Francisco. I love your github url (github.com/libre) and would like to use it for a big-ish open source project and few modules that I'm doing. Are you going to use it in the future? Otherwise, would you mind giving it to me? Of course I would leave the repository `css` as is now (:

If you want more information of the project please contact me at publicfrancisco@hotmail.com, since I wouldn't like to publicly reveal the specifics of the project yet but I have no problem with revealing them to you.

Cheers

**Comment by tuxy** [comment]
@franciscop Please send me some more details on what kind of project you are thinking on doing with this github repo. Then I can decide on release it it to you. Thank You!

**Comment by franciscop** [comment]
I'm doing [http://www.libre.university/](http://www.libre.university/) to allow me and my classmates to learn in an open way, but now the web is in really early development. From that url you probably understand why I'd love to do the programming in http://github.com/libre/university

It's based on node.js and express, with some hand-made libraries that I could not find pre-made or that were too complex/bug-ridden to use. I'd also like to release them as libre/LIBRARY but that's not so important actually.

Is it the kind of project that you'd like your github repo to become?

**Comment by tuxy** [comment]
Sounds good. What's your github repo username ?

**Comment by franciscop** [comment]
Thank you! "franciscop" is my github username

**Comment by tuxy** [comment]
Hmmm, I forgot I already had plans for this repo to code few projects on top of it. Here is example; https://github.com/libre/css/blob/master/char.css  I've decided to keep it for now. If I don't use it later I will think about releasing it to you. Sorry!

**Comment by franciscop** [comment]
But "/libre" it's not a repo, it's an organization. Would it be possible if you create "/libre/university" and give me that repository? So you keep "/libre" and everything else, including "/libre/css"

**Comment by tuxy** [comment]
I would have to see more of what you actually doing in order to consider doing this repo's.

**Comment by franciscop** [comment]
No problem, what do you want to see? What other information do you want?

**Comment by tuxy** [comment]
The website you showed me before was just a landing page without any info.
Show me source-code, documentation or whatever else you got done.

**Comment by franciscop** [comment]
Hi again. The website had a link to another page (the Spanish button is a link) but it was not ready to be shown really. It's not ready even now, when I've used it to give a [small course on HTML and CSS](http://es.libre.university/subject/Programaci%C3%B3n%20web) (in Spanish) but you can see it in action there.

I can email you a snapshot of the source code so far, but it's not ready to be released just yet as I put some keys some time ago and all the history is in Git so I need to clean up that mess...

In the meantime I made a small html editor for the website, [Modern Editor](http://github.com/franciscop/modern-editor), since I don't like any of the options available like CKEditor and such.

**Comment by tuxy** [comment]
Hey Francisco, looks good. Which repository would you like me to create 
inside "libre" ?

**Comment by franciscop** [comment]
I think with "university" I'm good, like `https://github.com/libre/university`. The only thing is I'd love to be the admin of that repository since it'll be the official one if that's possible.

**Comment by tuxy** [comment]
Alright buddy, I've created this repo for you with admin at 
https://github.com/libre/university Enjoy and please don't abuse it.

**Comment by tuxy** [comment]
Done!

**Comment by franciscop** [comment]
Awesome, thank you so much. I'll do my best and surely I won't abuse it (:
